### ISSUE TITLE
Error on plugin enable

### ISSUE THREAD

**Issue by Xenophilicy** [JackNoordhuis/DiscordRelay-PocketMine#2]
I got two different errors while enabling the latest release of your plugin as well as running your earlier one.

**OS: Windows**
**PMMP Version: v3.6.1**
**Plugin Version(s): v0.0.2-ALPHA & v0.0.1-ALPHA**

***
### Here is the first one
```
[23:50:24] [Server thread/CRITICAL]: RuntimeException: "Tried to register a relay channel twice!" (EXCEPTION) in "plugins/DiscordRelay/src/jacknoordhuis/discordrelay/models/RelayOptions" at line 87
```
### Here is the second one
```
[23:50:24] [Server thread/CRITICAL]: Error: "Call to a member function getTaskId() on null" (EXCEPTION) in "plugins/DiscordRelay/src/jacknoordhuis/discordrelay/DiscordRelay" at line 78
```

Hope to hear back soon! I look forward to using your plugin!

**Comment by JackNoordhuis** [comment]
The first error is caused by the plugin attempting to load it's default configuration files. Make sure you set up the plugin: https://github.com/JackNoordhuis/DiscordRelay-PocketMine/wiki/Configuring. The second error is caused as the plugin failed to start and then pocketmine attempts to disable it, this should never happen if the plugin loads the configuration correctly.

**Comment by Xenophilicy** [comment]
Thanks for the response, sadly I ran into another error when the plugin is enabling. Please see the attached code at the bottom to view my configuration file.
***
### Error report:
```
[02:37:11] [Server thread/CRITICAL]: RuntimeException: "Tried to register a relay channel twice!" (EXCEPTION) in "plugins/DiscordRelay/src/jacknoordhuis/discordrelay/models/RelayOptions" at line 87
```
I also got the second error again, but I assume that will disappear once we get this working.
***
### Settings file:
```yaml
###  Discord-Relay v0.0.2-ALPHA configuration file  ###
general:
  # The default channel messages are relayed to and from discord.
  # Will respect both relay-from-discord and relay-to-discord flags (can be set to only relay one way.)
  default-channel: 
  bot:
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  channels:
    - name: lobby-chat
      discord-id: 544790094461272065
      embed-color: 16771072
      options:
        embed: true
        relay-from-discord: true
        relay-to-discord: true
    - name: lobby-logs
      discord-id: 544794898046517249
      options:
        relay-to-discord: true
        relay-from-discord: false
        embed: true
        console-levels:
          info:
            embed-color: 16777215 # White - Info
          notice:
            embed-color: 2612166 # Aqua - Notice
          debug:
            embed-color: 10743551 # Light Aqua - Debug
    - name: error-reports
      discord-id: 544791880420818964
      options:
        embed: true
        embed-color: 16721408
        relay-to-discord: true
        relay-from-discord: false
        console-levels: [emergency, alert, critical, error]
```
